<picture>
  <source media="(prefers-color-scheme:dark)" srcset="https://raw.githubusercontent.com/lxfriday/lxfriday/output/output/github-contrlbution-grid-snake-dark.svg">
  <source media="(prefers-color-scheme:light)" srcset="https://raw.githubusercontent.com/lxfriday/lxfriday/output/output/github-contrlbution-grid-snake.svg">
  <img alt="github contribution grid snake animation" src="https://raw.githubusercontent.com/lxfriday/lxfriday/output/output/github-contrlbution-grid-snake.svg">
</picture>
